[tool.finecode]
presets = [
    { source = "fine_python_format" },
    { source = "fine_python_lint" },
    { source = "fine_python_test" },
    { source = "fine_toml_recommended" },
    { source = "fine_python_code_hierarchy" },
]

[tool.finecode.action.text_document_semantic_tokens]
source = "fine_semantic_tokens.TextDocumentSemanticTokensAction"
handlers = [
    { name = "dispatch", source = "fine_semantic_tokens.SemanticTokensDispatchHandler", env = "dev_workspace", dependencies = ["fine_semantic_tokens~=0.1.0a0"] },
]

[tool.finecode.action.text_document_semantic_tokens_python]
source = "fine_python_lang.TextDocumentSemanticTokensPythonAction"
handlers = [
    { name = "pyrefly", source = "fine_python_pyrefly.PyreflySemanticTokensHandler", env = "dev_no_runtime", dependencies = [
        "fine_python_pyrefly[jsonrpc]~=0.2.0a0",
    ] },
]

[tool.finecode.extension.fine_python_ruff]
dependencies_override = ["ruff==0.15.*"]
