[project]
name = "fine-python-module-exports"
version = "0.1.1"
description = ""
authors = [{ name = "Vladyslav Hnatiuk", email = "aders1234@gmail.com" }]
readme = "README.md"
requires-python = ">= 3.11, < 3.14"
dependencies = ["finecode_extension_api==0.1.3", "fine_python_ast==0.1.1"]
