# docs: docs/reference/actions.md
import dataclasses
import pathlib

import tomlkit
from packaging.specifiers import InvalidSpecifier, SpecifierSet
from packaging.version import InvalidVersion, Version

from finecode_extension_api import code_action
from finecode_extension_api.interfaces import (
    ifileeditor,
    ifilemanager,
    ilogger,
    iprojectactionrunner,
    iprojectinfoprovider,
)
from finecode_extension_api.resource_uri import resource_uri_to_path
from fine_envs.sync_toolchains_action import EnvToolchainAxis, SyncToolchainsRunResult
from fine_python_lang import (
    list_obtainable_python_interpreters_action,
    sync_python_interpreters_action,
)

GENERATED_COMMENT = (
    "generated by sync_toolchains from requires-python -- run sync_toolchains to update"
)

_LATEST_PATCH_SENTINEL = 999
"""Stands in for "the newest patch release of this minor" when matching a specifier.

An axis row is a minor series (``cpython@3.11``), but ``requires-python`` is matched
against full versions, and what ``create_env`` provisions for that row is the *newest*
patch of the series the provisioner can obtain. So the question a row has to answer is
not "does the string 3.11 satisfy the specifier" -- it never does for a patch-level
bound -- but "does the interpreter this row will produce satisfy it". Matching a high
sentinel patch models that: ``>=3.11.4`` keeps 3.11 (the provisioner installs 3.11.15),
and ``<3.11.5`` drops it (the provisioner would install 3.11.15, which violates the
bound and yields an env the project cannot use)."""


def canonicalize_interpreter(value: str) -> str:
    """Expand ADR-0047's version-only shorthand: ``3.11`` -> ``cpython@3.11``."""
    return value if "@" in value else f"cpython@{value}"


def _newest_patch_of(minor_series: Version) -> Version:
    """The version a ``<major>.<minor>`` axis row stands for, for specifier matching."""
    major, minor, *_ = minor_series.release
    return Version(f"{major}.{minor}.{_LATEST_PATCH_SENTINEL}")


def derive_interpreters(
    requires_python: str,
    obtainable_interpreters: list[str],
    max_supported_python: str | None = None,
    extra_interpreters: list[str] | None = None,
) -> list[str]:
    """Expand ``requires-python`` into canonical interpreter identities.

    ``requires-python`` is a specifier, not an enumeration, so it is expanded against
    *obtainable_interpreters* -- what the environment provisioner can actually get. An
    open upper bound (``>=3.11``), the correct form for a published package, is bounded
    by that set rather than rejected. The result therefore depends on something outside
    the specifier, which is exactly why it is persisted instead of recomputed during
    config resolution.

    The derived axis is CPython-only: ``requires-python`` constrains version and carries
    no implementation, so a PyPy row can never be derived from it. Extra interpreters are
    appended afterwards as an *input* to the source rather than a hand-edit of its
    output, which keeps regeneration idempotent and drift unambiguous.
    """
    try:
        specifier = SpecifierSet(requires_python)
    except InvalidSpecifier as error:
        raise code_action.ActionFailedException(
            f"project.requires-python is not a valid PEP 440 specifier: '{requires_python}'"
        ) from error

    try:
        ceiling = Version(max_supported_python) if max_supported_python else None
    except InvalidVersion as error:
        raise code_action.ActionFailedException(
            "max_supported_python is not a valid version:"
            f" '{max_supported_python}'"
        ) from error

    try:
        obtainable_cpython = sorted(
            (
                Version(identity.split("@", 1)[1])
                for identity in obtainable_interpreters
                if identity.startswith("cpython@")
            ),
        )
    except InvalidVersion as error:
        raise code_action.ActionFailedException(
            f"obtainable interpreter has an unparsable version: {error}"
        ) from error

    identities = [
        f"cpython@{version}"
        for version in obtainable_cpython
        if (ceiling is None or version <= ceiling)
        # matched as the newest patch of the series, not as the bare `X.Y` string,
        # which no patch-level bound can ever satisfy -- see _LATEST_PATCH_SENTINEL
        and specifier.contains(_newest_patch_of(version))
    ]

    if not identities:
        raise code_action.ActionFailedException(
            f"requires-python '{requires_python}' matches no obtainable CPython version"
            + (f" at or below {max_supported_python}" if ceiling else "")
        )

    for extra in extra_interpreters or []:
        canonical = canonicalize_interpreter(extra)
        if canonical not in identities:
            identities.append(canonical)

    return identities


@dataclasses.dataclass
class SyncPythonInterpretersHandlerConfig(code_action.ActionHandlerConfig):
    envs: list[str] = dataclasses.field(default_factory=list)
    """Envs whose interpreter axis is derived. Empty means none and the action is a no-op.

    Matrices stay opt-in (PRD-0003 R7): an env with no declared axis keeps running in a
    single environment with an unchanged result shape.

    An env either derives its axis or has one pinned, never both. The derived axis is
    written into the project's own definition file, and project config beats preset
    config -- so listing an env whose axis a preset pins materializes the derived axis
    over it, and the run reports that once, since the pin stops having any effect.
    Dropping the env from this list keeps the preset's axis instead. Deriving is also
    the only way to override a pinned axis at all: config layering can replace a key,
    never unset one."""
    max_supported_python: str | None = None
    """Cap the newest CPython to derive. None means no cap beyond what is obtainable."""
    extra_interpreters: list[str] = dataclasses.field(default_factory=list)
    """Interpreters to add beyond the derived CPython rows, e.g. ``["pypy@3.11"]``.

    ``requires-python`` constrains version only and carries no implementation, so a
    non-CPython row can never be derived from it."""


class SyncPythonInterpretersHandler(
    code_action.ActionHandler[
        sync_python_interpreters_action.SyncPythonInterpretersAction,
        SyncPythonInterpretersHandlerConfig,
    ]
):
    """Derive an env's interpreter axis from ``requires-python`` and write it out.

    The axis lands in the project's *own* definition file, once per project, rather than
    being shared from a preset. Two projects that end up with identical axes hold two
    facts that were derived independently from two ``requires-python`` values, not one
    shared fact copied twice -- raise one project's floor and its axis has to move
    alone. A preset also cannot host it in the general case: presets ship as packages,
    and a non-editable one lives inside a virtualenv that ``prepare-envs`` overwrites,
    so there is nothing durable to write to.

    The redundancy this leaves behind (many projects, identical generated lists) is the
    cheap kind -- generated, and guarded by ``check_toolchains``. What it buys is the
    expensive kind: a project states its own axis, so no preset bump can change which
    interpreters it tests on without a diff to review. That is the trade ADR-0053 was
    written to make; see its alternatives for why a preset-hosted, project-extended
    axis is rejected.
    """

    FILE_OPERATION_AUTHOR = ifileeditor.FileOperationAuthor(
        id="SyncPythonInterpretersHandler"
    )

    def __init__(
        self,
        config: SyncPythonInterpretersHandlerConfig,
        file_manager: ifilemanager.IFileManager,
        file_editor: ifileeditor.IFileEditor,
        project_info_provider: iprojectinfoprovider.IProjectInfoProvider,
        action_runner: iprojectactionrunner.IProjectActionRunner,
        logger: ilogger.ILogger,
    ) -> None:
        self.config = config
        self.file_manager = file_manager
        self.file_editor = file_editor
        self.project_info_provider = project_info_provider
        self.action_runner = action_runner
        self.logger = logger

    async def run(
        self,
        payload: sync_python_interpreters_action.SyncPythonInterpretersRunPayload,
        run_context: sync_python_interpreters_action.SyncPythonInterpretersRunContext,
    ) -> SyncToolchainsRunResult:
        if not self.config.envs:
            return SyncToolchainsRunResult()

        if payload.project_def_path is not None:
            project_def_path = resource_uri_to_path(payload.project_def_path)
        else:
            project_def_path = self.project_info_provider.get_current_project_def_path()

        # The project's own document is parsed directly here for the drift comparison and
        # write target below, rather than using the preset-merged config. The axis is
        # materialized *here* on purpose (ADR-0053): a project states its own axis, so
        # bumping a preset can never change the matrix without a diff in this repo. An
        # axis another layer supplies is therefore not "already up to date" -- it is an
        # axis this file has yet to take ownership of, so drift is measured against the
        # file we write to. tomlkit also round-trips comments and formatting.
        document = tomlkit.parse(
            await self.file_manager.get_content(file_path=project_def_path)
        )

        requires_python = document.get("project", {}).get("requires-python", None)
        if requires_python is None:
            raise code_action.ActionFailedException(
                f"project.requires-python not found in {project_def_path}, cannot derive"
                " the interpreter axis"
            )

        # Existence is checked against the *merged* config, not the raw document parsed
        # above: an env like a preset's matrix env (e.g. `testing`) is legitimately
        # declared entirely by a preset, with nothing written into this project's own
        # file. The raw document is still what drift is compared against and what gets
        # written to (see the comment below) -- only "does this env exist at all" needs
        # the merged view.
        merged_config = await self.project_info_provider.get_project_raw_config(
            project_def_path=project_def_path
        )

        # the provisioner decides what is derivable: a version it cannot obtain would
        # yield an env that cannot be created (ADR-0053)
        obtainable = await self.action_runner.run_action(
            action_type=iprojectactionrunner.ActionRef.from_type(
                list_obtainable_python_interpreters_action.ListObtainablePythonInterpretersAction
            ),
            payload=list_obtainable_python_interpreters_action.ListObtainablePythonInterpretersRunPayload(),
            meta=run_context.meta,
        )

        derived = derive_interpreters(
            requires_python=str(requires_python),
            obtainable_interpreters=obtainable.toolchains,
            max_supported_python=self.config.max_supported_python,
            extra_interpreters=self.config.extra_interpreters,
        )

        axes: list[EnvToolchainAxis] = []
        for env_name in self.config.envs:
            self._assert_env_declared(
                merged_config=merged_config,
                env_name=env_name,
                project_def_path=project_def_path,
            )
            declared = [
                canonicalize_interpreter(str(value))
                for value in self._declared_interpreters(
                    document=document, env_name=env_name
                )
            ]
            if not declared:
                self._warn_if_axis_from_another_layer(
                    merged_config=merged_config,
                    env_name=env_name,
                    project_def_path=project_def_path,
                )
            axes.append(
                EnvToolchainAxis(env_name=env_name, declared=declared, derived=derived)
            )

        stale_axes = [axis for axis in axes if axis.changed]
        if not payload.save or not stale_axes:
            return SyncToolchainsRunResult(axes=axes, saved=False)

        for axis in stale_axes:
            self._write_interpreters(
                document=document, env_name=axis.env_name, interpreters=axis.derived
            )
            self.logger.debug(
                f"Derived interpreter axis for env '{axis.env_name}': {', '.join(axis.derived)}"
            )

        async with self.file_editor.session(
            author=self.FILE_OPERATION_AUTHOR
        ) as session:
            await session.save_file(
                file_path=project_def_path, file_content=tomlkit.dumps(document)
            )

        return SyncToolchainsRunResult(axes=axes, saved=True)

    def _assert_env_declared(
        self,
        merged_config: dict,
        env_name: str,
        project_def_path: pathlib.Path,
    ) -> None:
        # envs are registered as dependency groups (ADR-0018) and the env table is
        # optional settings on top of that, so either one proves the env is real. Either
        # may be contributed entirely by a preset (e.g. a matrix env like `testing`), so
        # this is checked against the merged config rather than the raw project file.
        #
        # Once an env's axis is derived and known, config resolution expands a matrix
        # base into one concrete env per interpreter, named `<name>@<impl>-<version>`
        # (ADR-0047) -- the bare base name itself then no longer appears as a key. So a
        # matrix child of env_name counts as proof too, or every project would fail this
        # check on the run right after its first successful one.
        dependency_group_names = merged_config.get("dependency-groups", {})
        env_table_names = merged_config.get("tool", {}).get("finecode", {}).get(
            "env", {}
        )
        prefix = f"{env_name}@"
        declared = any(
            name == env_name or name.startswith(prefix)
            for name in (*dependency_group_names, *env_table_names)
        )
        if not declared:
            raise code_action.ActionFailedException(
                f"env '{env_name}' is configured for interpreter derivation but is not"
                f" declared in {project_def_path}"
            )

    def _warn_if_axis_from_another_layer(
        self,
        merged_config: dict,
        env_name: str,
        project_def_path: pathlib.Path,
    ) -> None:
        """Report an axis this file is about to take ownership of from another layer.

        A preset -- or a finecode-user.toml -- may declare `interpreters` too, and a
        later layer replaces an earlier one's list wholesale (read_configs.py). The
        derived axis is written into the project's own file, so it wins that merge and
        the other layer's axis stops having any effect. That is the intended precedence,
        and it is the only way a project can derive over an axis a preset pins, since a
        config key can be replaced but never unset. It is worth saying out loud once,
        though: otherwise the layer's declaration goes dead with nothing to notice it by.

        Detecting it relies on one fact: config resolution expands a matrix env into one
        `<name>@<impl>-<version>` child per interpreter before handing config to a
        handler (read_configs.py, ADR-0047), so children prove an axis exists somewhere.
        This file declaring none proves it is not here. A first run with no axis at all
        has no children and says nothing. Only the presence of children is read, never
        their order or values, so this survives any change to how they are built.
        """
        env_table = merged_config.get("tool", {}).get("finecode", {}).get("env", {})
        prefix = f"{env_name}@"
        if not any(name.startswith(prefix) for name in env_table):
            return

        self.logger.warning(
            f"Interpreter axis of env '{env_name}' is declared by another config layer"
            " (a preset, or a finecode-user.toml). The axis derived from requires-python"
            f" is being written into {project_def_path}, which takes precedence over it."
            f" To keep the other layer's axis instead, remove '{env_name}' from the"
            " 'envs' config of this handler."
        )

    def _declared_interpreters(
        self, document: tomlkit.TOMLDocument, env_name: str
    ) -> list[str]:
        env_table = (
            document.get("tool", {}).get("finecode", {}).get("env", {}).get(env_name, {})
        )
        return list(env_table.get("interpreters", []))

    def _write_interpreters(
        self, document: tomlkit.TOMLDocument, env_name: str, interpreters: list[str]
    ) -> None:
        tool = document.setdefault("tool", tomlkit.table(is_super_table=True))
        finecode = tool.setdefault("finecode", tomlkit.table(is_super_table=True))
        envs = finecode.setdefault("env", tomlkit.table(is_super_table=True))
        if env_name not in envs:
            envs[env_name] = tomlkit.table()

        array = tomlkit.array()
        array.extend(interpreters)
        array.comment(GENERATED_COMMENT)
        envs[env_name]["interpreters"] = array
