[tool.poetry]
name = "finecode-fine-format"
version = "0.1.0"
description = ""
authors = ["Vladyslav Hnatiuk <aders1234@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
finecode_black = { path = "../../actions/finecode_black" }
finecode_isort = { path = "../../actions/finecode_isort" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
