[tool.finecode.action.run_tests]
source = "fine_test.RunTestsAction"
handlers = [
    { name = "pytest", source = "fine_python_pytest.PytestRunTestsHandler", env = "dev", dependencies = [
        "fine_python_pytest~=0.1.0a0",
    ] },
]

[tool.finecode.action.list_tests]
source = "fine_test.ListTestsAction"
handlers = [
    { name = "pytest", source = "fine_python_pytest.PytestListTestsHandler", env = "dev", dependencies = [
        "fine_python_pytest~=0.1.0a0",
    ] },
]

[tool.finecode.extension.fine_python_pytest]
dependencies_override = ["pytest==9.0.*"]
