[tool.finecode.action.run_tests]
source = "finecode_extension_api.actions.run_tests.RunTestsAction"
handlers = [
    { name = "pytest", source = "fine_python_pytest.PytestRunTestsHandler", env = "dev", dependencies = [
        "fine_python_pytest~=0.1.0a0",
    ] },
]

[tool.finecode.action.list_tests]
source = "finecode_extension_api.actions.list_tests.ListTestsAction"
handlers = [
    { name = "pytest", source = "fine_python_pytest.PytestListTestsHandler", env = "dev", dependencies = [
        "fine_python_pytest~=0.1.0a0",
    ] },
]
