[tool.poetry]
name = "finecode"
version = "0.1.0"
description = ""
authors = ["Vladyslav Hnatiuk <aders1234@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
loguru = "^0.6.0"
tomlkit = "^0.11.7"
watchdog = "^3.0.0"
click = "^8.1.7"
pydantic = "^2.5.3"
command-runner = "^1.5.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
finecode_fine_py = { path = "presets/finecode_fine_py" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.finecode]
presets = [
    { source = "finecode_fine_py" }
]
