[tool.finecode]
presets = [{ source = "fine_code_hierarchy" }]


[tool.finecode.action.text_document_prepare_call_hierarchy_python]
source = "fine_python_lang.TextDocumentPrepareCallHierarchyPythonAction"

[[tool.finecode.action.text_document_prepare_call_hierarchy_python.handlers]]
name = "pyrefly"
source = "fine_python_pyrefly.PyreflyPrepareCallHierarchyHandler"
env = "dev_no_runtime"
dependencies = ["fine_python_pyrefly[jsonrpc]~=0.2.0a0"]


[tool.finecode.action.call_hierarchy_incoming_calls_python]
source = "fine_python_lang.CallHierarchyIncomingCallsPythonAction"

[[tool.finecode.action.call_hierarchy_incoming_calls_python.handlers]]
name = "pyrefly"
source = "fine_python_pyrefly.PyreflyCallHierarchyIncomingCallsHandler"
env = "dev_no_runtime"
dependencies = ["fine_python_pyrefly[jsonrpc]~=0.2.0a0"]


[tool.finecode.action.call_hierarchy_outgoing_calls_python]
source = "fine_python_lang.CallHierarchyOutgoingCallsPythonAction"

[[tool.finecode.action.call_hierarchy_outgoing_calls_python.handlers]]
name = "pyrefly"
source = "fine_python_pyrefly.PyreflyCallHierarchyOutgoingCallsHandler"
env = "dev_no_runtime"
dependencies = ["fine_python_pyrefly[jsonrpc]~=0.2.0a0"]


[tool.finecode.action.text_document_prepare_type_hierarchy_python]
source = "fine_python_lang.TextDocumentPrepareTypeHierarchyPythonAction"

[[tool.finecode.action.text_document_prepare_type_hierarchy_python.handlers]]
name = "pyrefly"
source = "fine_python_pyrefly.PyreflyPrepareTypeHierarchyHandler"
env = "dev_no_runtime"
dependencies = ["fine_python_pyrefly[jsonrpc]~=0.2.0a0"]


[tool.finecode.action.type_hierarchy_supertypes_python]
source = "fine_python_lang.TypeHierarchySupertypesPythonAction"

[[tool.finecode.action.type_hierarchy_supertypes_python.handlers]]
name = "pyrefly"
source = "fine_python_pyrefly.PyreflyTypeHierarchySupertypesHandler"
env = "dev_no_runtime"
dependencies = ["fine_python_pyrefly[jsonrpc]~=0.2.0a0"]


[tool.finecode.action.type_hierarchy_subtypes_python]
source = "fine_python_lang.TypeHierarchySubtypesPythonAction"

[[tool.finecode.action.type_hierarchy_subtypes_python.handlers]]
name = "pyrefly"
source = "fine_python_pyrefly.PyreflyTypeHierarchySubtypesHandler"
env = "dev_no_runtime"
dependencies = ["fine_python_pyrefly[jsonrpc]~=0.2.0a0"]


[tool.finecode.extension.fine_python_pyrefly]
dependencies_override = ["pyrefly==0.64.*"]


[[tool.finecode.service]]
interface = "finecode_extension_api.interfaces.ijsonrpcclient.IJsonRpcClient"
source = "finecode_jsonrpc.jsonrpc_client.JsonRpcClientImpl"
env = "dev_no_runtime"
dependencies = ["finecode_jsonrpc~=0.1.0a1"]

[[tool.finecode.service]]
interface = "finecode_extension_api.interfaces.ilspclient.ILspClient"
source = "finecode_extension_runner.impls.lsp_client.LspClientImpl"
env = "dev_no_runtime"
dependencies = []
