[project]
name = "fine-python-lint"
version = "0.1.0"
description = ""
authors = [{ name = "Vladyslav Hnatiuk", email = "aders1234@gmail.com" }]
readme = "README.md"
requires-python = ">=3.11, < 3.14"
dependencies = [
    "finecode @ git+ssh://git@github.com:finecode-dev/finecode.git",
    "fine_python_mypy @ git+ssh://git@github.com:finecode-dev/finecode.git#subdirectory=extensions/fine_python_mypy",
    "fine_python_flake8 @ git+ssh://git@github.com:finecode-dev/finecode.git#subdirectory=extensions/fine_python_flake8",
    "flake8-bugbear (>=24.12.12,<25.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
