[tool.poetry]
name = "fine_python_recommended"
version = "0.1.0"
description = ""
authors = ["Vladyslav Hnatiuk <aders1234@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fine_python_format = { path = "../fine_python_format" }
fine_python_lint = { path = "../fine_python_lint" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
