"""Translation of pyrefly error kinds and severities.

Pyrefly's own ``[errors]`` table is the model: the configured kind-to-severity
strings become ``--<severity>=`` flags for ``pyrefly check`` and entries in a
generated ``pyrefly.toml`` for the LSP server.
"""

from __future__ import annotations

import json
import tomllib
from collections.abc import Mapping
from pathlib import Path
from typing import Literal

__all__ = [
    "PyreflyErrorSeverity",
    "cli_severity_args",
    "dump_config_args",
    "find_project_pyrefly_config",
    "render_lsp_config",
]

PyreflyErrorSeverity = Literal["error", "warn", "info", "ignore"]

_SEVERITY_ORDER: tuple[PyreflyErrorSeverity, ...] = (
    "error",
    "warn",
    "info",
    "ignore",
)
# Ascending verbosity: `pyrefly check` hides anything below `error` unless
# `--min-severity` is lowered to the least severe configured kind.
_MIN_SEVERITY_ORDER: tuple[PyreflyErrorSeverity, ...] = ("info", "warn")


def cli_severity_args(errors: Mapping[str, PyreflyErrorSeverity]) -> list[str]:
    """Render the severity table as ``pyrefly check`` flags.

    One ``--<severity>=<kinds>`` flag per configured severity, in
    error/warn/info/ignore order with the kinds sorted, plus ``--min-severity``
    when a configured kind would otherwise stay hidden below pyrefly's default
    ``error`` floor.
    """
    args: list[str] = []
    for severity in _SEVERITY_ORDER:
        kinds = sorted(kind for kind, value in errors.items() if value == severity)
        if kinds:
            args.append(f"--{severity}={','.join(kinds)}")
    configured = set(errors.values())
    for severity in _MIN_SEVERITY_ORDER:
        if severity in configured:
            args.append(f"--min-severity={severity}")
            break
    return args


def find_project_pyrefly_config(project_dir: Path) -> Path | None:
    """Return the pyrefly config an upward walk from *project_dir* discovers.

    A ``pyrefly.toml`` wins over a ``pyproject.toml`` in the same directory; a
    ``pyproject.toml`` counts only when it parses and declares a ``[tool.pyrefly]``
    table. An unparseable ``pyproject.toml`` is skipped, matching pyrefly's own
    tolerance for project files without pyrefly configuration.
    """
    current = project_dir
    while True:
        pyrefly_toml = current / "pyrefly.toml"
        if pyrefly_toml.is_file():
            return pyrefly_toml
        pyproject_toml = current / "pyproject.toml"
        if pyproject_toml.is_file():
            try:
                data = tomllib.loads(pyproject_toml.read_text(encoding="utf-8"))
            except tomllib.TOMLDecodeError:
                data = None
            if data is not None:
                tool_section = data.get("tool")
                if isinstance(tool_section, dict) and isinstance(
                    tool_section.get("pyrefly"), dict
                ):
                    return pyproject_toml
        if current.parent == current:
            return None
        current = current.parent


def render_lsp_config(
    project_dir: Path, errors: Mapping[str, PyreflyErrorSeverity]
) -> str:
    """Render the generated ``pyrefly.toml`` that applies *errors* to the LSP server.

    The project includes are absolute because a config outside the project's own
    directory would otherwise resolve relative includes against its own location and
    silently report nothing; the excludes heuristic is disabled because the default
    excludes already contain every workspace source root.
    """
    project_glob = project_dir.as_posix()
    python_glob = json.dumps(f"{project_glob}/**/*.py")
    stub_glob = json.dumps(f"{project_glob}/**/*.pyi")
    lines = [
        (
            "# Generated by fine_python_pyrefly from the `PyreflyConfig`"
            " service's `errors` config. Do not edit."
        ),
        f"project-includes = [{python_glob}, {stub_glob}]",
        "disable-project-excludes-heuristics = true",
        "",
        "[errors]",
    ]
    lines.extend(
        f"{json.dumps(kind)} = {json.dumps(errors[kind])}" for kind in sorted(errors)
    )
    return "\n".join(lines) + "\n"


def dump_config_args(pyrefly_bin: Path, config_path: Path) -> list[str]:
    """Command that validates a generated pyrefly config.

    The config path doubles as the file argument on purpose: without one,
    ``dump-config`` enters project-checking mode and walks every file
    ``project-includes`` matches. That walk fails on files the LSP server
    itself tolerates (a broken symlink left by a stale ``build/``) and descends
    into the project's virtualenvs for nothing. A file argument keeps the
    config validation — an unknown kind or an invalid severity still fails —
    without the walk.
    """
    return [str(pyrefly_bin), "dump-config", "-c", str(config_path), str(config_path)]
