[tool.finecode.action.format_file]
source = "finecode_extension_api.actions.FormatFileAction"
handlers = [
    { name = "dispatch", source = "finecode_builtin_handlers.FormatFileDispatchHandler", env = "dev_no_runtime", dependencies = [
        "finecode_builtin_handlers~=0.2.0a1",
    ] },
    { name = "save", source = "finecode_builtin_handlers.SaveFormatFileHandler", env = "dev_no_runtime", dependencies = [
        "finecode_builtin_handlers~=0.2.0a1",
    ] },
]

[tool.finecode.action.format_python_file]
source = "finecode_extension_api.actions.FormatPythonFileAction"
handlers = [
    # ruff formatter doesn't handle imports, run isort to sort them first
    { name = "isort", source = "fine_python_isort.IsortFormatFileHandler", env = "dev_no_runtime", dependencies = [
        "fine_python_isort~=0.3.0a0",
    ] },
    { name = "ruff", source = "fine_python_ruff.RuffFormatFileHandler", env = "dev_no_runtime", dependencies = [
        "fine_python_ruff~=0.2.0a0",
    ] },
]

[[tool.finecode.action_handler]]
source = "fine_python_isort.IsortFormatFileHandler"
# make isort config compatible with fine_python_lint
# this config is based on 'black' profile of isort, black is not used in lint preset,
# but rules configured for ruff formatter are compatible with black formatting
config.multi_line_output = 3
config.include_trailing_comma = true
config.force_grid_wrap = 0
config.use_parentheses = true
config.ensure_newline_before_comments = true
config.line_length = 88
config.split_on_trailing_comma = true
