[tool.poetry]
name = "fine_python_format"
version = "0.1.0"
description = ""
authors = ["Vladyslav Hnatiuk <aders1234@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fine_python_black = { path = "../../actions/fine_python_black" }
fine_python_isort = { path = "../../actions/fine_python_isort" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
