[project]
name = "fine-python-format"
version = "0.1.0"
description = ""
authors = [{ name = "Vladyslav Hnatiuk", email = "aders1234@gmail.com" }]
readme = "README.md"
requires-python = ">=3.11, < 3.14"
dependencies = [
    "finecode @ git+ssh://git@github.com:Aksem/FineCode.git",
    "fine_python_black @ git+ssh://git@github.com:Aksem/FineCode.git#subdirectory=actions/fine_python_black",
    "fine_python_isort @ git+ssh://git@github.com:Aksem/FineCode.git#subdirectory=actions/fine_python_isort",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
