[tool.finecode.action.create_env]
source = "finecode_extension_api.actions.CreateEnvAction"

[[tool.finecode.action.create_env.handlers]]
name = "create_env_with_uv"
source = "fine_python_uv.UvCreateEnvHandler"
env = "dev_workspace"
dependencies = ["fine_python_uv~=0.1.0a0"]


[tool.finecode.action.create_envs]
source = "finecode_extension_api.actions.CreateEnvsAction"

[[tool.finecode.action.create_envs.handlers]]
name = "create_envs_discover_envs"
source = "finecode_builtin_handlers.CreateEnvsDiscoverEnvsHandler"
env = "dev_workspace"
dependencies = ["finecode_builtin_handlers~=0.2.0a0"]

[[tool.finecode.action.create_envs.handlers]]
name = "create_envs_dispatch"
source = "finecode_builtin_handlers.CreateEnvsDispatchHandler"
env = "dev_workspace"
dependencies = ["finecode_builtin_handlers~=0.2.0a0"]

[tool.finecode.action.install_env]
source = "finecode_extension_api.actions.InstallEnvAction"

[[tool.finecode.action.install_env.handlers]]
name = "install_env_read_config"
source = "finecode_builtin_handlers.InstallEnvReadConfigHandler"
env = "dev_workspace"
dependencies = ["finecode_builtin_handlers~=0.2.0a0"]

[[tool.finecode.action.install_env.handlers]]
name = "install_env_install_deps"
source = "finecode_builtin_handlers.InstallEnvInstallDepsHandler"
env = "dev_workspace"
dependencies = ["finecode_builtin_handlers~=0.2.0a0"]


[tool.finecode.action.install_envs]
source = "finecode_extension_api.actions.InstallEnvsAction"

[[tool.finecode.action.install_envs.handlers]]
name = "install_envs_discover_envs"
source = "finecode_builtin_handlers.InstallEnvsDiscoverEnvsHandler"
env = "dev_workspace"
dependencies = ["finecode_builtin_handlers~=0.2.0a0"]

[[tool.finecode.action.install_envs.handlers]]
name = "install_envs_dispatch"
source = "finecode_builtin_handlers.InstallEnvsDispatchHandler"
env = "dev_workspace"
dependencies = ["finecode_builtin_handlers~=0.2.0a0"]


[tool.finecode.action.dump_config]
source = "finecode_extension_api.actions.DumpConfigAction"

[[tool.finecode.action.dump_config.handlers]]
name = "dump_config"
source = "finecode_builtin_handlers.DumpConfigHandler"
env = "dev_workspace"
dependencies = ["finecode_builtin_handlers~=0.2.0a0"]


[[tool.finecode.action.dump_config.handlers]]
name = "dump_config_save"
source = "finecode_builtin_handlers.DumpConfigSaveHandler"
env = "dev_workspace"
dependencies = ["finecode_builtin_handlers~=0.2.0a0"]


[tool.finecode.action.install_deps_in_env]
source = "finecode_extension_api.actions.InstallDepsInEnvAction"

[[tool.finecode.action.install_deps_in_env.handlers]]
name = "install_deps_with_uv"
source = "fine_python_uv.UvInstallDepsInEnvHandler"
env = "dev_workspace"
dependencies = ["fine_python_uv~=0.1.0a0"]


[tool.finecode.action.list_src_artifact_files_by_lang]
source = "finecode_extension_api.actions.ListSrcArtifactFilesByLangAction"

[[tool.finecode.action.list_src_artifact_files_by_lang.handlers]]
name = "list_src_artifact_files_by_lang_python"
source = "fine_python_package_info.ListSrcArtifactFilesByLangPythonHandler"
env = "dev_no_runtime"
dependencies = ["fine_python_package_info~=0.2.0a0"]

[tool.finecode.action.group_src_artifact_files_by_lang]
source = "finecode_extension_api.actions.GroupSrcArtifactFilesByLangAction"

[[tool.finecode.action.group_src_artifact_files_by_lang.handlers]]
name = "group_src_artifact_files_by_lang_python"
source = "fine_python_package_info.GroupSrcArtifactFilesByLangPythonHandler"
env = "dev_no_runtime"
dependencies = ["fine_python_package_info~=0.2.0a0"]


[tool.finecode.action.lint]
source = "finecode_extension_api.actions.LintAction"

[[tool.finecode.action.lint.handlers]]
name = "lint"
source = "finecode_builtin_handlers.LintHandler"
env = "dev_no_runtime"
dependencies = ["finecode_builtin_handlers~=0.2.0a0"]

[tool.finecode.action.lint_files]
source = "finecode_extension_api.actions.LintFilesAction"

[[tool.finecode.action.lint_files.handlers]]
name = "lint_files_dispatch"
source = "finecode_builtin_handlers.LintFilesDispatchHandler"
env = "dev_no_runtime"
dependencies = ["finecode_builtin_handlers~=0.2.0a0"]

[tool.finecode.action.format_file]
source = "finecode_extension_api.actions.FormatFileAction"

[tool.finecode.action.format_python_file]
source = "finecode_extension_api.actions.FormatPythonFileAction"

[tool.finecode.action.format]
source = "finecode_extension_api.actions.FormatAction"

[[tool.finecode.action.format.handlers]]
name = "format"
source = "finecode_builtin_handlers.FormatHandler"
env = "dev_no_runtime"
dependencies = ["finecode_builtin_handlers~=0.2.0a0"]

[tool.finecode.action.format_files]
source = "finecode_extension_api.actions.FormatFilesAction"

[[tool.finecode.action.format_files.handlers]]
name = "format_files_iterate"
source = "finecode_builtin_handlers.FormatFilesIterateHandler"
env = "dev_no_runtime"
dependencies = ["finecode_builtin_handlers~=0.2.0a0"]

[tool.finecode.action.install_git_hooks]
source = "finecode_extension_api.actions.InstallGitHooksAction"

[[tool.finecode.action.install_git_hooks.handlers]]
name = "install_git_hooks"
source = "finecode_builtin_handlers.InstallGitHooksHandler"
env = "dev_workspace"
dependencies = ["finecode_builtin_handlers~=0.2.0a0"]


[tool.finecode.action.uninstall_git_hooks]
source = "finecode_extension_api.actions.UninstallGitHooksAction"

[[tool.finecode.action.uninstall_git_hooks.handlers]]
name = "uninstall_git_hooks"
source = "finecode_builtin_handlers.UninstallGitHooksHandler"
env = "dev_workspace"
dependencies = ["finecode_builtin_handlers~=0.2.0a0"]


[tool.finecode.action.clean_finecode_logs]
source = "finecode_extension_api.actions.CleanFinecodeLogsAction"

[[tool.finecode.action.clean_finecode_logs.handlers]]
name = "clean_finecode_logs_dev_workspace"
source = "finecode_builtin_handlers.CleanFinecodeLogsHandler"
env = "dev_workspace"
dependencies = ["finecode_builtin_handlers~=0.2.0a0"]

[[tool.finecode.action.clean_finecode_logs.handlers]]
name = "clean_finecode_logs_dev_no_runtime"
source = "finecode_builtin_handlers.CleanFinecodeLogsHandler"
env = "dev_no_runtime"
dependencies = ["finecode_builtin_handlers~=0.2.0a0"]

# TODO: finish
# [[tool.finecode.action.clean_finecode_logs.handlers]]
# name = "clean_finecode_logs_dev"
# source = "finecode_builtin_handlers.CleanFinecodeLogsHandler"
# env = "dev"
# dependencies = ["finecode_builtin_handlers~=0.1.0a0"]

# [[tool.finecode.action.clean_finecode_logs.handlers]]
# name = "clean_finecode_logs_runtime"
# source = "finecode_builtin_handlers.CleanFinecodeLogsHandler"
# env = "runtime"
# dependencies = ["finecode_builtin_handlers~=0.1.0a0"]
