[tool.finecode.action.text_document_semantic_tokens]
source = "fine_semantic_tokens.TextDocumentSemanticTokensAction"

[[tool.finecode.action.text_document_semantic_tokens.handlers]]
name = "dispatch"
source = "fine_semantic_tokens.SemanticTokensDispatchHandler"
env = "dev_workspace"
dependencies = ["fine_semantic_tokens~=0.1.0a0"]
