[tool.finecode]
presets = [{ source = "fine_inlay_hints" }]


[[tool.finecode.action.text_document_inlay_hint.handlers]]
name = "dispatch"
source = "fine_inlay_hints.InlayHintDispatchHandler"
env = "dev_workspace"
dependencies = ["fine_inlay_hints~=0.1.0a0"]


[tool.finecode.action.text_document_inlay_hint_python]
source = "fine_python_lang.TextDocumentInlayHintPythonAction"

[[tool.finecode.action.text_document_inlay_hint_python.handlers]]
name = "pyrefly"
source = "fine_python_pyrefly.PyreflyInlayHintHandler"
env = "dev_no_runtime"
dependencies = ["fine_python_pyrefly[jsonrpc]~=0.2.0a0"]


[tool.finecode.extension.fine_python_pyrefly]
dependencies_override = ["pyrefly==1.1.*"]


[[tool.finecode.service]]
interface = "finecode_extension_api.interfaces.ijsonrpcclient.IJsonRpcClient"
source = "finecode_jsonrpc.jsonrpc_client.JsonRpcClientImpl"
env = "dev_no_runtime"
dependencies = ["finecode_jsonrpc~=0.1.0a1"]

[[tool.finecode.service]]
interface = "finecode_extension_api.interfaces.ilspclient.ILspClient"
source = "finecode_extension_runner.impls.lsp_client.LspClientImpl"
env = "dev_no_runtime"
dependencies = []
