[tool.finecode]
presets = [
    { source = "fine_python_recommended" },
    { source = "fine_git_hooks" },
    { source = "fine_logs" }
]

# currently, all packages in finecode repository are pure python packages, reuse
# setuptools build in all of them
[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

# TODO: recognize minimal python version automatically
[[tool.finecode.action_handler]]
source = "fine_python_ruff.RuffLintFilesHandler"
config.target_version = 'py311'

[[tool.finecode.action_handler]]
source = "fine_python_pyrefly.PyreflyLintFilesHandler"
config.python_version = '3.11'

[tool.finecode.action.init_repository_provider]
source = "fine_dist_artifacts.InitRepositoryProviderAction"
handlers = [
    { name = 'init_repository_provider', source = 'fine_dist_artifacts.InitRepositoryProviderHandler', env = "dev_no_runtime", dependencies = [
        "fine_dist_artifacts~=0.1.0a0",
    ] },
]

[tool.finecode.action.publish_artifact]
source = "fine_dist_artifacts.PublishArtifactAction"
handlers = [
    { name = 'publish_artifact', source = 'fine_dist_artifacts.PublishArtifactHandler', env = "dev_no_runtime", dependencies = [
        "fine_dist_artifacts~=0.1.0a0",
    ] },
]

[tool.finecode.action.get_src_artifact_version]
source = "fine_src_artifacts.GetSrcArtifactVersionAction"
handlers = [
    { name = 'get_src_artifact_version_py', source = 'fine_python_package_info.GetSrcArtifactVersionPyHandler', env = "dev_no_runtime", dependencies = [
        "fine_python_package_info~=0.2.0a1",
    ] },
]

[tool.finecode.action.get_dist_artifact_version]
source = "fine_dist_artifacts.GetDistArtifactVersionAction"
handlers = [
    { name = 'get_dist_artifact_version_py', source = 'fine_python_package_info.GetDistArtifactVersionPyHandler', env = "dev_no_runtime", dependencies = [
        "fine_python_package_info~=0.2.0a1",
    ] },
]

[tool.finecode.action.get_src_artifact_registries]
source = "fine_src_artifacts.GetSrcArtifactRegistriesAction"
handlers = [
    { name = 'get_src_artifact_registries_py', source = 'fine_python_package_info.GetSrcArtifactRegistriesPyHandler', env = "dev_no_runtime", dependencies = [
        "fine_python_package_info~=0.2.0a1",
    ] },
]

[tool.finecode.action.publish_artifact_to_registry]
source = "fine_dist_artifacts.PublishArtifactToRegistryAction"
handlers = [
    { name = 'publish_artifact_to_registry_py', source = 'fine_python_package_info.PublishArtifactToRegistryPyHandler', env = "dev_no_runtime", dependencies = [
        "fine_python_package_info~=0.2.0a1",
    ] },
]

[tool.finecode.action.is_artifact_published_to_registry]
source = "fine_dist_artifacts.IsArtifactPublishedToRegistryAction"
handlers = [
    { name = 'is_artifact_published_to_registry_py', source = 'fine_python_package_info.IsArtifactPublishedToRegistryPyHandler', env = "dev_no_runtime", dependencies = [
        "fine_python_package_info~=0.2.0a1",
    ] },
]

[tool.finecode.action.build_artifact]
source = "fine_src_artifacts.BuildArtifactAction"
handlers = [
    { name = 'build_artifact_py', source = 'fine_python_package_info.BuildArtifactPyHandler', env = "dev_no_runtime", dependencies = [
        "fine_python_package_info~=0.2.0a1",
    ] },
]

[tool.finecode.action.ingest_wal_to_store]
source = "fine_wal_events.IngestWalToStoreAction"
handlers = [
    { name = "discover_sources", source = "fine_wal_explorer.IngestWalSourceDiscoveryHandler", env = "wal_explorer", dependencies = ["fine_wal_explorer~=0.1.0a0"] },
    { name = "ingest_wal_to_store", source = "fine_wal_explorer.IngestWalToStoreHandler", env = "wal_explorer", dependencies = ["fine_wal_explorer~=0.1.0a0"] },
]

[tool.finecode.action.discover_wal_sources]
source = "fine_wal_events.DiscoverWalSourcesAction"
handlers = [
    { name = "discover_wal_sources", source = "fine_wal_explorer.DiscoverWalSourcesHandler", env = "wal_explorer", dependencies = ["fine_wal_explorer~=0.1.0a0"] },
]

[tool.finecode.action.verify_artifact_published_to_registry]
source = "fine_dist_artifacts.VerifyArtifactPublishedToRegistryAction"
# TODO: install, try to import etc
handlers = []

[tool.finecode.action.publish_and_verify_artifact]
source = "finecode_dev_extensions.publish_and_verify_artifact_action.PublishAndVerifyArtifactAction"
handlers = [
    { name = 'init_repository_provider', source = 'finecode_dev_extensions.PublishAndVerifyArtifactInitRepositoryProviderHandler', env = "dev_no_runtime", dependencies = [
        "finecode_dev_extensions~=0.2.0a0",
    ] },
    { name = 'publish_and_verify_artifact', source = 'finecode_dev_extensions.PublishAndVerifyArtifactHandler', env = "dev_no_runtime", dependencies = [
        "finecode_dev_extensions~=0.2.0a0",
    ] },
]
