[tool.finecode]
presets = [
    { source = "fine_python_recommended" },
    { source = "fine_python_aksem" },
]

# in development finecode can only be started with local version of finecode_extension_runner,
# otherwise version conflict occurs, because versions of finecode and
# finecode_extension_runner must match
[tool.finecode.env.runtime.dependencies]
finecode_extension_runner = { path = "../../../finecode_extension_runner", editable = true }

[tool.finecode.env.dev.dependencies]
finecode_extension_runner = { path = "../../../finecode_extension_runner", editable = true }

[tool.finecode.env.dev_no_runtime.dependencies]
finecode_extension_runner = { path = "../../../finecode_extension_runner", editable = true }

# currently, all packages in finecode repository are pure python packages, reuse
# setuptools build in all of them
[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"
