# docs: docs/reference/actions.md
import dataclasses

from finecode_extension_api import code_action, textstyler
from finecode_extension_api.resource_uri import ResourceUri


@dataclasses.dataclass
class LockDependenciesRunPayload(code_action.RunActionPayload):
    src_artifact_def_path: ResourceUri
    """``file://`` URI of the artifact definition file (e.g. pyproject.toml, package.json)."""
    output_dir: ResourceUri
    """``file://`` URI of the directory where lock files will be written. The handler decides the filenames."""


class LockDependenciesRunContext(
    code_action.RunActionContext[LockDependenciesRunPayload]
): ...


@dataclasses.dataclass
class LockDependenciesRunResult(code_action.RunActionResult):
    # All lock files generated by this invocation (one for single-lock, N for multi-lock).
    lock_file_paths: list[ResourceUri]

    def update(self, other: code_action.RunActionResult) -> None:
        if not isinstance(other, LockDependenciesRunResult):
            return

        self.lock_file_paths = other.lock_file_paths

    def to_text(self) -> str | textstyler.StyledText:
        paths = "\n".join(self.lock_file_paths)
        return f"Locked dependencies to:\n{paths}"

    @property
    def return_code(self) -> code_action.RunReturnCode:
        return code_action.RunReturnCode.SUCCESS


class LockDependenciesAction(
    code_action.Action[
        LockDependenciesRunPayload,
        LockDependenciesRunContext,
        LockDependenciesRunResult,
    ]
):
    """Generate a lock file pinning an artifact's dependencies to exact versions."""

    DESCRIPTION = "Generate a lock file pinning an artifact's dependencies to exact versions."
    PAYLOAD_TYPE = LockDependenciesRunPayload
    RUN_CONTEXT_TYPE = LockDependenciesRunContext
    RESULT_TYPE = LockDependenciesRunResult
