from typing import Protocol


class IUserMessenger(Protocol):
    def warning(self, message: str) -> None: ...

    def error(self, message: str) -> None: ...

    def info(self, message: str) -> None: ...
